src/Perso/UgliestBundle/Entity/Photo.php
<?php

namespace Perso\UgliestBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Photo
 *
 * @ORM\Table()
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Photo {
	/**
	 *
	 * @var integer @ORM\Column(name="id", type="integer")
	 *      @ORM\Id
	 *      @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;
	
	/**
	 *
	 * @var string @ORM\Column(name="url", type="string", length=255)
	 */
	private $url;
	
	/**
	 *
	 * @var string @ORM\Column(name="alt", type="string", length=255)
	 */
	private $alt;
	private $file;
	
	// On ajoute cet attribut pour y stocker le nom du fichier temporairement
	private $tempFilename;
	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId() {
		return $this->id;
	}
	
	/**
	 * Set url
	 *
	 * @param string $url        	
	 * @return Photo
	 */
	public function setUrl($url) {
		$this->url = $url;
		
		return $this;
	}
	
	/**
	 * Get url
	 *
	 * @return string
	 */
	public function getUrl() {
		return $this->url;
	}
	
	/**
	 * Set alt
	 *
	 * @param string $alt        	
	 * @return Photo
	 */
	public function setAlt($alt) {
		$this->alt = $alt;
		
		return $this;
	}
	
	/**
	 * Get alt
	 *
	 * @return string
	 */
	public function getAlt() {
		return $this->alt;
	}
		
	/**
	 * Get file
	 *
	 * @return string
	 */
	public function getFile() {
		return $this->file;
	}
	
	// On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
	public function setFile(UploadedFile $file) {
		$this->file = $file;
		
		// On vérifie si on avait déjà un fichier pour cette entité
		if (null !== $this->url) {
			// On sauvegarde l'extension du fichier pour le supprimer plus tard
			$this->tempFilename = $this->url;
			
			// On réinitialise les valeurs des attributs url et alt
			$this->url = null;
			$this->alt = null;
		}
	}
	
	/**
	 * @ORM\PrePersist()
	 * @ORM\PreUpdate()
	 */
	public function preUpload() {
		// Si jamais il n'y a pas de fichier (champ facultatif)
		if (null === $this->file) {
			return;
		}
		
		// Le nom du fichier est son id, on doit juste stocker également son extension
		// Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
		$this->url = $this->file->guessExtension ();
		
		// Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
		$this->alt = $this->file->getClientOriginalName ();
	}
	
	/**
	 * @ORM\PostPersist()
	 * @ORM\PostUpdate()
	 */
	public function upload() {
		// Si jamais il n'y a pas de fichier (champ facultatif)
		if (null === $this->file) {
			return;
		}
		
		// Si on avait un ancien fichier, on le supprime
		if (null !== $this->tempFilename) {
			$oldFile = $this->getUploadRootDir () . '/' . $this->id . '.' . $this->tempFilename;
			if (file_exists ( $oldFile )) {
				unlink ( $oldFile );
			}
		}
		
		// On déplace le fichier envoyé dans le répertoire de notre choix
		$this->file->move ( $this->getUploadRootDir (), 		// Le répertoire de destination
		$this->id . '.' . $this->url );		// Le nom du fichier à créer, ici « id.extension »
		
	}
	
	/**
	 * @ORM\PreRemove()
	 */
	public function preRemoveUpload() {
		// On sauvegarde temporairement le nom du fichier, car il dépend de l'id
		$this->tempFilename = $this->getUploadRootDir () . '/' . $this->id . '.' . $this->url;
	}
	
	/**
	 * @ORM\PostRemove()
	 */
	public function removeUpload() {
		// En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
		if (file_exists ( $this->tempFilename )) {
			// On supprime le fichier
			unlink ( $this->tempFilename );
		}
	}
	public function getUploadDir() {
		// On retourne le chemin relatif vers l'image pour un navigateur
		return 'uploads/img';
	}
	protected function getUploadRootDir() {
		// On retourne le chemin relatif vers l'image pour notre code PHP
		return __DIR__ . '/../../../../web/' . $this->getUploadDir ();
	}
	public function getWebPath() {
		return $this->getUploadDir () . '/' . $this->getId () . '.' . $this->getUrl ();
	}
}

src/Perso/UgliestBundle/Controller/DefaultController.php
<?php

namespace Perso\UgliestBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;


use Perso\UgliestBundle\Entity\Person;


use Perso\UgliestBundle\Form\PersonType;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('PersoUgliestBundle:Default:index.html.twig');
    }
    
    public function createAction()
    {
       
		$person = new Person ();
		
		// On crée le formulaire grâce à l'ArticleType
		$form = $this->createForm ( new PersonType (), $person );
		
		// On récupère la requête
		$request = $this->getRequest ();
		
		// On vérifie qu'elle est de type POST
		if ($request->getMethod () == 'POST') {
			// On fait le lien Requête <-> Formulaire
			$form->bind ( $request );
			
			// On vérifie que les valeurs entrées sont correctes
			// (Nous verrons la validation des objets en détail dans le prochain chapitre)
			if ($form->isValid ()) {
				// On enregistre notre objet $article dans la base de données
				$em = $this->getDoctrine ()->getManager ();
				$em->persist ( $person );
				$em->flush ();
				
				// On définit un message flash
				$this->get ( 'session' )->getFlashBag ()->add ( 'info', 'Congratulations, user added !' );
				
				// On redirige vers la page de visualisation de l'article nouvellement créé
				return $this->redirect ( $this->generateUrl ( 'perso_ugliest_compare' ) );
			}
		}
		
		// À ce stade :
		// - Soit la requête est de type GET, donc le visiteur vient d'arriver sur la page et veut voir le formulaire
		// - Soit la requête est de type POST, mais le formulaire n'est pas valide, donc on l'affiche de nouveau
		
		return $this->render ( 'PersoUgliestBundle:Default:create.html.twig', array (
				'form' => $form->createView () 
		) );
    }
    
    public function listAction()
    {
        // On récupère les articleCompetence pour l'article $article
        $list_persons = $this->getDoctrine ()->getManager ()->getRepository ( 'PersoUgliestBundle:Person' )->findAll();
    
        // Puis modifiez la ligne du render comme ceci, pour prendre en compte les variables :
        return $this->render ( 'PersoUgliestBundle:Default:list.html.twig', array (
                    'list_persons' => $list_persons
               ) );
    }
    
    public function compareAction(Person $person=null)
    {
        // On récupère les articleCompetence pour l'article $article
        $list_persons = $this->getDoctrine ()->getManager ()->getRepository ( 'PersoUgliestBundle:Person' )->findAll();
        
        //On sélectionne deux clés au hasard
        $random_key = array_rand($list_persons, 2);
        
        //contient le nom des personnes sélectionnées
        $list_versus[] = $list_persons[$random_key[0]];
        $list_versus[] = $list_persons[$random_key[1]];
        
        //c'est ici que l'ont incrémente le nombre de points su quelqu'un existe
        if($person != null){
            $person->increasePoints();
            
            $em = $this->getDoctrine ()->getManager ();
            $em->persist ( $person );
            $em->flush ();
            
            // Puis on recommence l'action de départ
            return $this->redirect ( $this->generateUrl ( 'perso_ugliest_compare'  ) );
            
        }else {
            // Puis modifiez la ligne du render comme ceci, pour prendre en compte les variables :
            return $this->render ( 'PersoUgliestBundle:Default:compare.html.twig', array (
                    'list_versus' => $list_versus,
                    
            ) );
       } 
            
    }
    
    public function rankingAction()
    {
        // On récupère les articleCompetence pour l'article $article
        $list_persons = $this->getDoctrine ()->getManager ()->getRepository ( 'PersoUgliestBundle:Person' )->getAllOrderPoints();
    
        // Puis modifiez la ligne du render comme ceci, pour prendre en compte les variables :
        return $this->render ( 'PersoUgliestBundle:Default:ranking.html.twig', array (
                'list_persons' => $list_persons
        ) );
    }
}

src/Perso/UgliestBundle/Resources/views/Default/compare.html.twig
{% extends "::layout.html.twig" %} 

{% block body %}
    <h2>
      Select the ugliest face
    </h2>
    
    {% for person in list_versus %}
        
        <a  href="{{ path('perso_ugliest_compare', {'id': person.id}) }}">
            <div class="col-lg-5"
                 style="border-radius: 6px; border: 1px solid #AAA; background-color: #CCC; line-height: 40px; text-align: center; padding-top: 8px;"d   
                 onclick="$( this ).fadeOut();"
            >
                {% if person.photo is not null %}
                    <img style="max-width: 250px;"
        				src="{{ asset(person.photo.webPath) }}"
          				alt="{{ person.photo.alt }}"
          				class="img-circle"
        			/> 
                {% endif %} 
                <br />
                {{ person.surname }} {{ person.name }}
            </div>
        </a> 
        
        {% if not loop.last %}
            <div class="col-lg-2">
                
            </div>
        {% endif %}
        
    {% endfor %}

{% endblock %}


{% block javascripts %}
    <script>  
        $('#compare').addClass('active')
    </script>
{% endblock %}

src/Perso/UgliestBundle/Resources/views/Default/create.html.twig
{% extends "::layout.html.twig" %} 

{% block title %}{{
	parent() }} - Create
{% endblock %} 

{% block body %}
	<div class="container">
		{# Le formulaire reste inchangé #}
		<div class="well">
  			<form method="post" {{ form_enctype(form) }}>
   				{{ form_widget(form) }}
   			 	<input type="submit" class="btn btn-primary" />
  			</form>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
    <script> $('#create').addClass('active')</script>
{% endblock %}

src/Perso/UgliestBundle/Resources/views/Default/index.html.twig
{% extends "::layout.html.twig" %} 

{% block title %}
	{{parent() }} - Index
{% endblock %} 

{% block body %}
   

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Hello you!</h1>
              <p> Welcome to my first website! </p>
              <br />
              </div>
          </div>
        </div>
        <div class="item">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>An active Website!</h1>
              <p>NEW : top 3! Thanks to it, everyone will be able to know WHO IS THE UGLIEST! Click the "ranking" tab above.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>To know more</h1>
              <p>Please, click the links below.</p>
              <p>
                <a href="https://plus.google.com/+MaximeBourdel09/posts">  
                    <button class="btn btn-md btn-googleplus">
                        <i class="fa fa-google-plus"> Google+</i>
                    </button>
                </a>
                <a href="https://www.facebook.com/maxime.bourdel">  
                    <button class="btn btn-md btn-facebook">
                        <i class="fa fa-facebook"> Facebook</i>
                    </button>
                </a>
                <a href="https://www.linkedin.com/profile/view?id=342130999&trk=nav_responsive_tab_profile_pic">  
                    <button class="btn btn-md btn-linkedin">
                        <i class="fa fa-linkedin"> Linked In</i> 
                    </button> 
                </a> 
                 <a href=" https://github.com/maximebourdel">  
                    <button class="btn btn-md btn-github">
                        <i class="fa fa-github-square"> Github</i>
                    </button>
                </a>  
              </p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- One column of text below the carousel -->
      <div class="row">
          <div class="col-lg-4 col-lg-offset-4">
              <img class="img-circle" src="../../../resources/img/photoPro.jpeg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
              <h2>This is me</h2>
              <p>This website is done for everyone, but not made to make fun of people.</p>
          </div>
      </div><!-- /.row -->
    </div>



{% endblock %}

{% block javascripts %}
    <script> $('#home').addClass('active')</script>
{% endblock %}

src/Perso/UgliestBundle/Resources/views/Default/list.html.twig
{% extends "::layout.html.twig" %} 

{% block body %}
    <h2>
      Here are the all the competitors
    </h2>
    
    <section class="row placeholders">
        {% for person in list_persons %}
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"
             style="border-radius: 6px; line-height: 40px; text-align: center; padding-top: 8px;"
        >
            {% if person.photo is not null %}
                <img style="max-width: 150px;"
    				src="{{ asset(person.photo.webPath) }}"
      				alt="{{ person.photo.alt }}"
      				class="img-circle"
    			/> 
            {% endif %}
            <div class="col-lg-12" style="max-height: 40px;" >
                {{ (person.surname ~ ' ' ~ person.name)[:17]}}
            </div>   
        </div>
      {% endfor %}
    </section>

{% endblock %}


{% block javascripts %}
    <script> $('#list').addClass('active')</script>
{% endblock %}

src/Perso/UgliestBundle/Resources/views/Default/ranking.html.twig
{% extends "::layout.html.twig" %} 

{% block title %}
	{{parent() }} - Index
{% endblock %} 

{% block body %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        
        <h1 class="page-header">TOP 3</h1>

        <div class="row placeholders">
        
            <div class="col-xs-6 col-sm-3 placeholder">
                <img style="max-width: 200px;"
    				src="{{ asset(list_persons[1].photo.webPath) }}"
      				alt="{{ list_persons[1].photo.alt }}"
      				class="img-circle"
    			 /> 
                <h4 class="text-center" style="border-radius:5px; line-height: 25px; margin-top: 55px; padding-top: 80px; text-align: center;background-color:silver;">Second</h4>
                <p class="text-muted text-center">{{ list_persons[1].points }} points</p>
            </div>
            
            <div class="col-xs-6 col-sm-3 placeholder">
                <img style="max-width: 200px;"
    				src="{{ asset(list_persons[0].photo.webPath) }}"
      				alt="{{ list_persons[0].photo.alt }}"
      				class="img-circle"
    			 /> 
                <h4 class="text-center" style="border-radius:5px; line-height: 25px; padding-top: 125px; text-align: center;background-color:gold;">First</h4>
                <p class="text-muted text-center">{{ list_persons[0].points }} points</p>
            </div>
            
            <div class="col-xs-6 col-sm-3 placeholder">
                <img style="max-width: 200px;"
    				src="{{ asset(list_persons[2].photo.webPath) }}"
      				alt="{{ list_persons[2].photo.alt }}"
      				class="img-circle"
    			/> 
                <h4 class="text-center" style="border-radius:5px; line-height: 25px; margin-top: 100px; padding-top: 35px; text-align: center;background-color:peru;">Third</h4>
                <p class="text-muted text-center">{{ list_persons[2].points }} points</p>
            
            </div>
            
        </div>
        
    </div>      
    
    
    <h2 class="sub-header">Complete list</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Points</th>
                    <th>Photo</th>
                </tr>
            </thead>
            <tbody>
            {% for person in list_persons %}
                <tr 
                    {% if loop.index == 1  %} style="background-color:gold;" {% endif %}
                    {% if loop.index == 2  %} style="background-color:silver;" {% endif %}
                    {% if loop.index == 3  %} style="background-color:peru;" {% endif %}
                >
                  <td>{{ loop.index }}</td>
                  <td>{{ person.name }}</td>
                  <td>{{ person.surname }}</td>
                  <td>{{ person.points }}</td>
                  <td>
                      <img style="max-width: 30px;"
        				src="{{ asset(person.photo.webPath) }}"
          				alt="{{ person.photo.alt }}"
          				class="img-circle"
        	          />
        	          {% if loop.first %}
                          <i class="glyphicon glyphicon-star"></i>
                      {% endif %} 
    			  </td>
                </tr>   
            {% endfor %}
            </tbody>
        </table>
    </div>
    
{% endblock %}

{% block javascripts %}
    <script> $('#ranking').addClass('active')</script>
{% endblock %}